PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

# Delete any leftovers of previous schemata
#DROP GRAPH <http://example.org/LOVInferred>;

# Find all predicates used in the current dataset and their equivalents and generalizations
INSERT {
  ?s ?p ?o
}
WHERE {
  {
    SERVICE ?service{
        {
            ?graph{
              SELECT DISTINCT ?s ?p ?o
              WHERE {
                   ?s ?p ?o.
                   FILTER (STRSTARTS(str(?s), "http://www.courses.matfyz.sk/ontology#")).
                   FILTER (?p = rdf:type).
                   FILTER (?o = rdfs:Class).
                    FILTER EXISTS {
                                                 SELECT ?s
                                                      WHERE {
                                      ?a ?n ?s.
                                      FILTER (STRSTARTS(str(?a), "http://www.w3.org/2002/07/owl") || STRSTARTS(str(?a), "http://www.courses.matfyz.sk/ontology#") ).
                                      FILTER ( ?n = schema:domainIncludes || ?n = schema:rangeIncludes).}
                                      }
              }}
        }
    }
  }
};


INSERT {
  ?s ?p ?o
}
WHERE {
  {
    SERVICE ?service{
        {
            ?graph{
             SELECT DISTINCT ?s ?p ?o
              WHERE {
                   ?s ?p ?o.
                   FILTER (STRSTARTS(str(?s), "http://www.w3.org/2002/07/owl") || STRSTARTS(str(?s), "http://www.courses.matfyz.sk/ontology#") ).
                   FILTER ( ?p = schema:domainIncludes || ?p = schema:rangeIncludes || ?p = rdfs:subClassOf).
              }}
        }
    }
  }
};


INSERT {
  ?s ?p ?o
}
WHERE {
  {
    SERVICE ?service{
        {
            ?graph{
             SELECT DISTINCT ?s ?p ?o
              WHERE {
                   ?s ?p ?o.
                   FILTER (STRSTARTS(str(?s), "http://www.w3.org/2002/07/owl") || STRSTARTS(str(?s), "http://www.courses.matfyz.sk/ontology#") ).
                   FILTER ( ?p = rdf:type ).
                   FILTER ( ?o = rdf:Property || ?o = owl:DatatypeProperty || ?o = owl:ObjectProperty ).
              }}
        }
    }
  }
};
